### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by cgreenberg** [GMMTeam/GMM#1]
I'm trying to compile on an AMD linux machine running Fedora. I have boost version 1.54. I get these compile errors (well, many more, these are the first few). Maybe the version of boost I have is incorrect?:

Linking CXX executable trainGMM
CMakeFiles/trainGMM.dir/Model_ADAPT.cpp.o: In function `loadConfiguration(int, char**, OPTIONS&, CModelAdapt::OPTIONS&)':
Model_ADAPT.cpp:(.text+0xead): undefined reference to`boost::program_options::variables_map::variables_map()'
Model_ADAPT.cpp:(.text+0xebb): undefined reference to `boost::program_options::options_description::m_default_line_length'
Model_ADAPT.cpp:(.text+0xec6): undefined reference to`boost::program_options::options_description::m_default_line_length'
Model_ADAPT.cpp:(.text+0xf0b): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
Model_ADAPT.cpp:(.text+0x13f0): undefined reference to`boost::program_options::options_description::add_options()'
Model_ADAPT.cpp:(.text+0x1410): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
Model_ADAPT.cpp:(.text+0x1425): undefined reference to`boost::program_options::options_description_easy_init::operator()(char const_, boost::program_options::value_semantic const_, char const_)'
Model_ADAPT.cpp:(.text+0x143a): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const_, boost::program_options::value_semantic const_, char const_)'
Model_ADAPT.cpp:(.text+0x144f): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
Model_ADAPT.cpp:(.text+0x1464): undefined reference to`boost::program_options::options_description_easy_init::operator()(char const_, boost::program_options::value_semantic const_, char const_)'
Model_ADAPT.cpp:(.text+0x1479): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const_, boost::program_options::value_semantic const_, char const_)'

**Comment by GMMTeam** [comment]
Hi Charles,
Thanks for report,
I will look on it. It is definitely by the boost.

Jan

**Comment by GMMTeam** [comment]
Hi Charles,
I hope that I have found what is going on.
The native Find_package script in cmake doesn't work well in most cases. 
I have tested it, and I got the same heap of errors.
I set the boost manually and it works. My setup in the main 
CMakeLists.txt is folowing:

# Boost available from: http://www.boost.org/users/download/

#FIND_PACKAGE(Boost REQUIRED)

# if FIND_PACKAGE not able to locate the Boost dirs, comment the

previous line and

# you can try to specify the paths to boost include and lib directories

manually,

# uncomment and adjust following three lines:

SET (BOOST_ROOT "/afs/ics.muni.cz/software/boost-1.55") #####EDIT THESE 
THREE LINES
SET (Boost_INCLUDE_DIRS "${BOOST_ROOT}/include")
SET (Boost_LIBRARY_DIRS "${BOOST_ROOT}/lib")

# in some builds following boost-libs has to be specified (uncomment if

necessary)
SET (Boost_MY_LIB_FILES
     "boost_filesystem"
     "boost_system"
     "boost_program_options"
     "boost_thread"
)

Hope it helps also for you...

Jan

**Comment by cgreenberg** [comment]
Ah ok, that worked, thanks!
