### ISSUE TITLE
Any suggestions on loading binary data from numpy?

### ISSUE THREAD

**Issue by cgreenberg** [GMMTeam/GMM#2]
How can I save 3D points from numpy such that they'd be readable? When I try to save an Nx3 array with numpy's [tofile](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html), I get this error:

Modul name: GMM-ESTIMATOR
=-=-=-=-=-=-=-=-=-=-=-=-=
Modul version: 5.2 (May 5th, 2014)

 Reading train data ...  done

 Loading data ...  done in 0.000105s
 TRAINING -> 
        Estimating model 
        (fullcov = 0, robust = 0, nummix = 4, log-lik-th = 0) [SSE Estimation ON]
 ERROR: TrainFromScratch(): Not enough data to model training.

**Comment by cgreenberg** [comment]
I tried doing this, where `data` is a 3000x3 array:

``` python
import numpy as np
fd = open('mypts.dat', 'wb')
ashape = np.array(data.shape)
ashape.tofile(fd,format='int32')     # writing data shape
nrows = ashape[0]
for nrow in range(nrows):            # writing rows
    data[nrow,:].tofile(fd,format='float')
fd.close()
```

And then loading it with trainGMM:

``` bash
~trainGMM -v -i mypts.dat --data-T 2 --type 0 --nummix 4 --it-EM 8 -o myModel.gmm -T --SSE --numThrd 4
```

And I get the error stated above (not enough data).

**Comment by GMMTeam** [comment]
On 11.12.2014 4:10, Charles Greenberg wrote:

> I tried doing this, where |data| is a 3000x3 array:
> 
> fd=  open('mypts.dat','wb')
> ashape=  np.array(data.shape)
> ashape.tofile(fd,format='int32')# writing data shape
> nrows=  ashape[0]
> for  nrowin  range(nrows):# writing rows
>      data[nrow,:].tofile(fd,format='float')
> fd.close()
> 
> And then loading it with trainGMM:
> 
> ~trainGMM -v -i mypts.dat --data-T 2 --type 0 --nummix 4 --it-EM 8 -o myModel.gmm -T --SSE --numThrd 4
> 
> And I get the error stated above (not enough data).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/GMMTeam/GMM/issues/2#issuecomment-66563056.Web 
> Bug from 
> https://github.com/notifications/beacon/AHSsLRtjsibcCNAE4z_FG0PiRxSDKP9-ks5nWQKigaJpZM4DG5r8.gif
> 
> Please check if the header was written correctly in 4-byte integers. My 
> python 2.7 writes it in 8-byte, ignoring the 'int32' format. Try to 
> convert the 'ashape' variable to uint32 in advance:

ashape=  np.array(data.shape)

**Comment by GMMTeam** [comment]
Sorry, I have pasted wrong line. The correct one is:
ashape = np.uint32(data.shape)

**Comment by cgreenberg** [comment]
thanks, that seems to work.
