### ISSUE TITLE
What is the GMM output format?

### ISSUE THREAD

**Issue by cgreenberg** [GMMTeam/GMM#4]
E.g. here is the output of a 4-component full-covariance trained model. I assume that after the "4" you have the weight, center, then the covariance matrix for each component. But the matrices are 3x4, so I'm not sure what they mean.

```
3
   1.000000e+00
   1.000000e+00
   1.000000e+00
4
   3.607388e-01 F

   4.116591e+01
   1.353769e+01
  -5.620205e+01

   1.638246e+02    1.638246e+02    3.539832e+01   -3.431795e+00
   1.031694e+02    3.539832e+01    1.031694e+02    8.941883e-01
   6.452498e+01   -3.431795e+00    8.941883e-01    6.452498e+01

   2.350436e-01 F

   3.309999e+01
   9.985276e+00
  -1.757933e+01

   1.053156e+02    1.053156e+02    1.444269e+00    2.408809e+01
   1.873979e+02    1.444269e+00    1.873979e+02    4.640942e+01
   5.061274e+01    2.408809e+01    4.640942e+01    5.061274e+01

   2.030136e-01 F

   5.506852e+01
  -3.919311e+00
  -4.148125e+01

   8.984534e+01    8.984534e+01    1.770672e+01    2.543674e+01
   9.894402e+01    1.770672e+01    9.894402e+01    3.425658e+01
   8.381673e+01    2.543674e+01    3.425658e+01    8.381673e+01

   2.012040e-01 F

   5.432072e+01
   7.004661e+00
  -1.428557e+01

   8.078023e+01    8.078023e+01   -1.220675e+01    4.434660e+00
   1.432270e+02   -1.220675e+01    1.432270e+02    1.766816e+00
   5.795630e+01    4.434660e+00    1.766816e+00    5.795630e+01
```

**Comment by GMMTeam** [comment]
GMM txt output format:
Yes, there are two curiosities, mostly to hold backward compatibility 
with our old model format:
1) at the begining - is dimension and a vector of scale factors (default 
all ones)
2) full-covariances are marked by 'F' after component weight, and the 
first extra column is a copy of diagonal of the matrix. It allows to 
read the diagonal part of the full-covariance model by scripts/programs 
that supports the diagonal GMMs only.

You may inspect the LoadGMM matlab function in the IOscripts directory 
for details.

**Comment by cgreenberg** [comment]
Great, thanks!
