### ISSUE TITLE
Variational inference?

### ISSUE THREAD

**Issue by cgreenberg** [GMMTeam/GMM#5]
Question: are you planning to implement variational inference? I.e. using a prior on each component to discover the correct number needed for a data set. As I understand this doesn't necessarily increase the computation time very much.

**Comment by GMMTeam** [comment]
Thanks for the comment, It is nice to hear thinks like that.

Answer: "A proper number of components" algorithm is already implemented 
in the project. You may turn it on by "--robust" parameter. "--numix" 
than mean the maximum number of components. The implementation is based 
on two of my papers:

Jan Vaněk and Lukáš Machlica and Josef Psutka : Estimation of 
Single-Gaussian and Gaussian Mixture Models for Pattern Recognition . 
18th Iberoamerican Congress on Pattern Recognition, Lecture Notes in 
Computer Science, Springer, 2013.
http://www.kky.zcu.cz/en/publications/JanVanek_2013_Estimationof

  Jan Vaněk and Lukáš Machlica and Josef V. Psutka and Josef Psutka : 
Covariance Matrix Enhancement Approach to Train Robust Gaussian Mixture 
Models of Speech Data . Speech and Computer, Lecture Notes in Computer 
Science, vol. 8113, p. 92-99, Springer, 2013.
http://www.kky.zcu.cz/en/publications/JanVanek_2013_CovarianceMatrix

**Comment by cgreenberg** [comment]
Question about the robust parameter. The LL seems to fluctuate up and down after generating many components. Should I be increasing the --ll-Th option to something above 0?

**Comment by GMMTeam** [comment]
You are right.
LL in the "robust" case may fluctuate for model with many components. 
Therefore, --ll-Th should be a small positive constant to omit this 
fluctuations and to suppress "a numerical noise" introduced by rounding 
errors. I use usually --ll-Th 0.02 or 0.01. However, it may be set to 
zero for small models with no problem.

**Comment by cgreenberg** [comment]
Excellent, makes sense. Another question - do you have an idea of how to decide the number of EM steps per cycle to use? Your example uses 8, but it's not totally clear how to decide the right number to use. Thanks.

**Comment by GMMTeam** [comment]
One should use "enough" iterations :-)
The EM algorithm converges, therefore too much iteration is no problem. 
In the "classic" case where a GMM is trained from scratch, a threshold 
for LL improvement can be introduced. However, in the "robust" case or 
in the case of reestimation of existing/external model, larger number of 
iteration is needed. Therefore, we keep the manual setting of the number 
of iterations in config.
Magic numbers guide:
- 8 for classic GMM from scratch
- 20 for robust variant or reestimation of existing model
